version: '2'

services:

### Code Box ###
    homestead:
        build:
            context: .
        ports:
            - "8000:80" # web
            - "2222:22" # ssh
        volumes:
            - ../bp:/var/www/html/ascent
        # env_file: .env
        restart: always
