version: '2'

services:

### Homestead Box ###
    homestead:
        image: majuansari/dockerstead:base
        # build:
        #     context: .
        ports:
            - "8000:80" # web
            - "2222:22" # ssh
            - "33306:3306"
        volumes:
            - ../ascent:/var/www/html/ascent #configure your project director path here
        # env_file: .env
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
         - PMA_ARBITRARY=1
        restart: always
        ports:
         - 8001:80
        volumes:
         - /sessions